import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WhatupContact from "./components/WhatupContact";
import Footer from './components/Footer'
import Header from "./components/Header";
import Toolbar from "./components/Toolbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center justify-between min-h-screen`}
      >
        <Header/>
        <Toolbar />
        <div className="flex-1 w-full flex flex-col items-center">
          {children}
        </div>
        <Footer />
        <div className="fixed bottom-10 right-10 z-50">
          <WhatupContact />
        </div>
      </body>
    </html>
  );
}
